### ISSUE TITLE
unnecessary "readonly" in index.d.ts

### ISSUE THREAD

**Issue by paraself** [sindresorhus/open#135] opened 2019-05-19 08:43 UTC
https://github.com/sindresorhus/open/blob/6751082d8ac0929d4bd29a5812d71cd2c4a43bad/index.d.ts#L33

```readonly app?: string | readonly string[];```
should be changed to 
```readonly app?: string | string[];```

Otherwise TS compiler is giving errors
```
[TS] node_modules/open/index.d.ts(33,36): error TS1005: ';' expected.
[TS] node_modules/open/index.d.ts(33,43): error TS1011: An element access expression should take an argument.
[TS] node_modules/open/index.d.ts(35,1): error TS1128: Declaration or statement expected.
[TS] 4:42:03 PM - Found 3 errors. Watching for file changes.
```

**Comment by sindresorhus** [comment] 2019-05-19 08:59
Duplicate of #130

**Closed by sindresorhus** 2019-05-19 08:59 UTC
