### ISSUE TITLE
Empty catch block is breaking the build

### ISSUE THREAD

**Issue by Gaurav-Balyan** [sindresorhus/open#286] opened 2022-06-03 23:20 UTC
### **What is expected?**
I should be able to use open package and it should not break my build.

**Steps to reproduce**
Empty catch break on line 38 is breaking my build. If I pass an argument within the catch block it works fine.

**Comment by sindresorhus** [comment] 2022-06-04 09:06
Duplicate of #284

**Closed by sindresorhus** 2022-06-04 09:06 UTC

**Comment by Gaurav-Balyan** [comment] 2022-06-04 10:06
I agree with you but I have one question.

Even if the empty catch block is intended, it is a good practice to write that as a comment in the empty catch to document the intention.

Any specific reason why you choose not to do that?
