### ISSUE TITLE
Is there a way for the program to wait until the page loads?

### ISSUE THREAD

**Issue by friendlymaninthisworld** [sindresorhus/open#254] opened 2021-06-01 22:25 UTC
So I'm new to Javascript so I may not know everything yet, but is there a way for the program to wait for the page to load.
Like I open a page using "open(config.url);", but then it waits before executing the next command. 

Is there already a command or do I use something else?

**Comment by sindresorhus** [comment] 2021-06-02 08:21
Duplicate of #178

**Closed by sindresorhus** 2021-06-02 08:21 UTC
