### ISSUE TITLE
TypeScript Error: Declaration or statement expected

### ISSUE THREAD

**Issue by codejamninja** [sindresorhus/open#142] opened 2019-06-29 19:50 UTC
I get the following typescript error when trying to generate documentation using sphinx-js.
https://github.com/mozilla/sphinx-js

```
Using TypeScript 3.2.4 from /usr/local/share/.config/yarn/global/node_modules/typedoc/node_modules/typescript/lib
Error: /home/codejamninja/Projects/sphinxdoc/node_modules/open/index.d.ts(32)
 ';' expected.
Error: /home/codejamninja/Projects/sphinxdoc/node_modules/open/index.d.ts(32)
 An element access expression should take an argument.
Error: /home/codejamninja/Projects/sphinxdoc/node_modules/open/index.d.ts(34)
 Declaration or statement expected.
```

**Comment by codejamninja** [comment] 2019-06-29 19:51
I think it has something to do with the following line, because when I remove it, the error goes away.

```ts
    readonly app?: string | readonly string[];
```
https://github.com/sindresorhus/open/blob/master/index.d.ts#L33

**Comment by codejamninja** [comment] 2019-06-29 19:52
If I change it to the following, it fixes it.

```ts
    readonly app?: string | string[];
```

**Comment by sindresorhus** [comment] 2019-06-29 19:53
Duplicate of #130

**Closed by sindresorhus** 2019-06-29 19:53 UTC
